### ISSUE TITLE
Planetary chat messages appear as Universe ones, without time stamps

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#23] opened 2016-07-30 05:51 UTC
Hi,

Since Starbound 1.0.3 hit, I saw some planetary chat messages appear in universe chat, having no time stamps.
The snippet below is the log right after one "should-be" planetary message showed in universe chat.

http://pastebin.com/agubmvuz

**Comment by ghost** [comment] 2016-07-31 09:02
Side note: I just had this issue lingering for more than 5 minutes, and noticed the player count on starbound-servers.net was showing wrong stats(such as NA / 114, when the actual capacity was set to 60). This may be a coincidence.

**Comment by kharidiron** [comment] 2016-08-07 18:39
Have you had any more of these? My guess is this is a problem resulting from a player not being fully wrappered, since the error is `AttributeError: 'StarryPyServer' object has no attribute 'player'`.

In my runs, I haven't had this happen yet, so I'm hopeful that this might just be a weird instance. Reproducibility is key to bug fixing.

**Comment by ghost** [comment] 2016-08-07 21:22
Unfortunately, I am still having this issue.

Apparently it happens when a player says something in local chat and another player joins the server almost at the same time.

(log snippet)
http://pastebin.com/KeHCnmSe

(game screenshot)
https://puu.sh/qteE9/1c6566b78f.png

**Comment by kharidiron** [comment] 2016-08-07 22:54
That sounds like a specific problem, and not a general one.

Is it happening for _every_ player who joins the server, or only a specific handful.

Can you look through the logs and verify if it is always the same player(s) or just a general issue.

**Comment by ghost** [comment] 2016-08-08 21:38
Since the last report, I have seen this issue caused by 3 different players. It might be hard to replicate the issue a lot since the entire player population is dwindling, but I will keep watching.

**Comment by GermaniumSystem** [comment] 2016-08-11 00:24
We're seeing this issue or something similar quite a lot on FBR. /l seems to work fine, but the /local toggle often sends a normal local message and a universe message without timestamp. Here's a section of debug.log from a particularly bad string of weird messages: http://pastebin.com/raw/nt7us6Sq

**Comment by kharidiron** [comment] 2016-09-09 05:42
With the new chat system in place, I'd like to revisit this issue, and know if it is still causing problems.

From SBReddit, I've yet to observe this, so it is hard for me to put a finger on what is going wrong.

**Comment by kharidiron** [comment] 2016-09-20 03:00
Is this still an issue? I'd like to close this ticket if the new local/party/universe chat is considered to be working sufficiently.

**Comment by GermaniumSystem** [comment] 2016-09-20 04:25
If it is still an issue, my community hasn't been very vocal about it. We've been through some fun worst-case scenarios and, as far as I'm aware, it hasn't cropped up.

I have seen some issues with chat_enhancements failing to handle a renamed player's messages, but it's minor and probably deserving of a separate issue - if any issue at all.

**Comment by ghost** [comment] 2016-09-20 05:09
I haven't seen this since StarryPy3k has been updated for Starbound 1.1.0. The new implementation has been working perfect.

**Comment by kharidiron** [comment] 2016-09-20 05:52
Okie doke, I'm going to close this issue then.

Check the newest commit for a fix with IRC escaping that is happening. (big oops on my part)

**Closed as completed by kharidiron** 2016-09-20 05:52 UTC
Labels: bug
