### ISSUE TITLE
StarryPy3k's RAM usage skyrockets after several minutes of operation

### ISSUE THREAD

**Issue by ghost** [kharidiron/StarryPy3k#17] opened 2016-07-25 04:20 UTC
In addition to what the title says, some players say they experience lag spikes from time to time. Though I'm not sure if this is due to Starbound itself or StarryPy3k, I thought this might be worth mentioning.

At the very moment a player said he was having a lag, StarryPy3k's log read as follows.
http://pastebin.com/srt4Nf8U

**Comment by kharidiron** [comment] 2016-07-26 04:04
StarryPy's packet parser has a mechanism for caching packets for reuse (since parsing packets is an expensive operation). The problem is, the code to reap old packets is currently broken in the code, leading to the case of run-away-memory usage that we are observing.

The fix for this is forth-coming.

**Comment by kharidiron** [comment] 2016-07-26 08:10
So far, on my server, this has made a huge cut into memory usage by StarryPy. I'd like to have more feedback from the community as well, if that is the case for them.

**Comment by davoodinator** [comment] 2016-07-27 11:50
yes StarryPy barely tickles the memory on my server now

**Closed as completed** 2016-07-28 06:33 UTC
Labels: bug
